# Generated by Django 3.2.3 on 2021-05-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("uid", models.UUIDField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("is_admin", models.BooleanField(default=False)),
            ],
        ),
    ]
